### ISSUE TITLE
creating floor plans programmatically

### ISSUE THREAD

**Issue by mathieujobin** [openfloorplan/ofp-viewer#7]
Hey @kriscarle 

sorry to be creating an issue while I actually want to ask you couple of questions. I wasn't sure how else to get hold of you. and this is related.

I just found your project, looking for an opensource solution to create and display floorplans.
I saw you also have an editor, I presume its a UI allowing to create floorplans. but I dont like UI editors, dragging stuff around with a mouse. There are several company trying to offer that service...

anyway, what I'd like to do, is create some sort of domain specific language, maybe in ruby, to generate whatever file your viewer can display.

on your readme, you are talking about a missing app/media folder, but I am not seeing anywhere you mention what I can place in that folder? does it look like a specific filename? what format are supported?

I see you linked to physics.ohio-state.edu floorplans. these are sure great examples. but DWG are binary, I would not know how to generate these things...

I see you mention a bit of SVG... does your viewer accept SVG ? or turn DWG into SVG ?

I guess, If I am able to generate floorplans in SVG, I could then just pipe it in imagemagick and have png of them ?

Do you have any suggestion for me? is your viewer a good fit for what I'm trying to do?

thanks

**Comment by hesanxu512** [comment]
I can not find the  app/media folder,I want to test the whole example .

**Comment by kriscarle** [comment]
The app/media folder wasn't included, unfortunately I don't have the SVG versions of the floor plans anymore.  This code was intended to work with SVGs exported from CAD floor plans like the AutoCAD DWG files and allow them to be interactive in the browser (pan/zoom/hover/click/dynamic styling/etc). You can use the open-source GDAL ogr2ogr tool to convert DWGs http://www.gdal.org/drv_cad.html
